name: News Collection Pipeline

on:
  schedule:
    # Run every hour at the 15th minute
    - cron: '15 * * * *'
  # Allow manual triggering too
  workflow_dispatch:

jobs:
  collect-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: |
        python -m playwright install --with-deps

    - name: Test OpenAI Connectivity
      run: curl -v https://api.openai.com/v1/models
       
    - name: Run news collection pipeline
      run: python pipeline.py
      env:
        GITHUB_ACTIONS: "true"
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
